### PR TITLE
Fix reporting errors from Oban

### LINKED ISSUE #63: Handler ErrorTracker.Integrations.Oban has failed and has been detached
Hi! I'm seeing this in the logs and I'm not sure why that's happening.

I'm using these versions:
    
    elixir 1.14.5
    erlang 25.3.2.10
    phoenix 1.7.12
    oban 2.18.2
    oban_pro 1.4.11
    oban_web 2.10.5
    error_tracker 0.2.2

## Development logs

```
[error] Handler ErrorTracker.Integrations.Oban has failed and has been detached. Class=:error
Reason={:badkey, :file, nil}
Stacktrace=[
  {ErrorTracker.Error, :new, 3,
   [file: 'lib/error_tracker/schemas/error.ex', line: 32]},
  {ErrorTracker, :report, 3, [file: 'lib/error_tracker.ex', line: 106]},
  {:telemetry, :"-execute/3-fun-0-", 4,
   [
     file: '/Users/jaime/code/myapp/deps/telemetry/src/telemetry.erl',
     line: 160
   ]},
  {:lists, :foreach_1, 2, [file: 'lists.erl', line: 1442]},
  {Oban.Queue.Executor, :emit_event, 1,
   [file: 'lib/oban/queue/executor.ex', line: 284]},
  {Oban.Queue.Executor, :"-call/1-fun-0-", 1,
   [file: 'lib/oban/queue/executor.ex', line: 84]},
  {Oban.Backoff, :with_retry, 3, [file: 'lib/oban/backoff.ex', line: 108]},
  {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 89]},
  {Task.Supervised, :reply, 4, [file: 'lib/task/supervised.ex', line: 34]},
  {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}
]
```

## Staging server logs

```
2024-08-23T07:46:01.833662+00:00 app[web.1]: 07:46:01.833 [error] Handler ErrorTracker.Integrations.Oban has failed and has been detached. Class=:error
2024-08-23T07:46:01.833679+00:00 app[web.1]: Reason={:badkey, :file, nil}
2024-08-23T07:46:01.833680+00:00 app[web.1]: Stacktrace=[
2024-08-23T07:46:01.833680+00:00 app[web.1]: {ErrorTracker.Error, :new, 3,
2024-08-23T07:46:01.833681+00:00 app[web.1]: [file: 'lib/error_tracker/schemas/error.ex', line: 32]},
2024-08-23T07:46:01.833682+00:00 app[web.1]: {ErrorTracker, :report, 3, [file: 'lib/error_tracker.ex', line: 106]},
2024-08-23T07:46:01.833683+00:00 app[web.1]: {:telemetry, :"-execute/3-fun-0-", 4,
2024-08-23T07:46:01.833683+00:00 app[web.1]: [file: '/tmp/build_477b1e97/deps/telemetry/src/telemetry.erl', line: 160]},
2024-08-23T07:46:01.833684+00:00 app[web.1]: {:lists, :foreach_1, 2, [file: 'lists.erl', line: 1442]},
2024-08-23T07:46:01.833684+00:00 app[web.1]: {Oban.Queue.Executor, :emit_event, 1,
2024-08-23T07:46:01.833684+00:00 app[web.1]: [file: 'lib/oban/queue/executor.ex', line: 284]},
2024-08-23T07:46:01.833685+00:00 app[web.1]: {Oban.Queue.Executor, :"-call/1-fun-0-", 1,
2024-08-23T07:46:01.833685+00:00 app[web.1]: [file: 'lib/oban/queue/executor.ex', line: 84]},
2024-08-23T07:46:01.833685+00:00 app[web.1]: {Oban.Backoff, :with_retry, 3, [file: 'lib/oban/backoff.ex', line: 108]},
2024-08-23T07:46:01.833686+00:00 app[web.1]: {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 89]}
2024-08-23T07:46:01.833686+00:00 app[web.1]: ]
```

### PR DESCRIPTION
**Pull request by odarriba**
There was an error when an Oban worker returned an `{:error, reason}` tuple because Oban does not return an stacktrace (makes sense, as it is not an exception by itself).

Our code was not prepared for that use case. I modified it to handle it and circumvent the needed for source file and source function information.

After this change, empty stack traces and source information are not shown on the dashboard to avoid confusion.

As an extra feature I have also added the reporting of the `state` of the job (which is mostly ever `failure` for us).

## How to test

The way to reproduce it is to have an Oban worker which returns a tuple `{:error, any()}` or just `:error`.

That use case generates an exception in the latest release and works as expected on this branch.

---

Closes #63

### CODE REVIEW

**Comment by jaimeiniesta** [comment]
Hey, that works great! I have tested this branch and now the error is tracked, and I can see the job details in the error context, as expected.

Thanks! 🚀

File: lib/error_tracker/web/live/show.ex [hunk 1]
```diff
@@ -121,4 +121,7 @@ defmodule ErrorTracker.Web.Live.Show do
     |> limit(^num_results)
     |> Repo.all()
   end
+
+  defp error_has_source_info?(%Error{source_function: "-", source_line: "-"}), do: false
+  defp error_has_source_info?(%Error{}), do: true
```
Comment (crbelaus) [inline lib/error_tracker/web/live/show.ex:126]: Maybe we can move this function to `ErrorTracker.Error.has_source_info?` so we can reuse it both in show and dashboard templates. We are currently using it in the show template but doing the check manually in the dashboard template.

What do you think?

**Review by crbelaus — APPROVED** [review]
I've tested it before and after the change and it works perfectly. 

I am wondering if we should add Oban as an optional dependency and create a test for this. Mainly to ensure that newer Oban versions don't break our assumptions.

Anyway this can be done later so feel free to merge it as-is.

File: lib/error_tracker/web/live/show.ex (hunk 1 above)
Comment (odarriba) [reply lib/error_tracker/web/live/show.ex]: Updated in https://github.com/elixir-error-tracker/error-tracker/pull/70/commits/e658416b4a8597cad0377c99c76cfc17d6743c9b
