### PR TITLE
Don't import private function name from router

### LINKED ISSUE #90: Router conflict with PhoenixAnalytics
The following error pops up when used with phoenix analytics
```bash
error: function parse_options/2 imported from both PhoenixAnalytics.Web.Router and ErrorTracker.Web.Router, call is ambiguous
```

Would it be possible to move the function parse_options/2 to another module and not import it?

https://github.com/lalabuy948/PhoenixAnalytics/issues/2

### PR DESCRIPTION
**Pull request by crbelaus**
Underscored functions are never imported by default. This should fix #90.

If you import the router on `main` you will see that the `parse_options` function is imported automatically:

```elixir
iex(1)> import ErrorTracker.Web.Router
ErrorTracker.Web.Router
iex(2)> h parse_options
No documentation for ErrorTracker.Web.Router.parse_options was found
```

If you do the same now you will se that the function is not imported and it tries to find it in the Kernel module.

```elixir
iex(1)> import ErrorTracker.Web.Router
ErrorTracker.Web.Router
iex(2)> h __parse_options__/2
No documentation for Kernel.__parse_options__/2 was found
```

### CODE REVIEW

File: lib/error_tracker/web/router.ex [hunk 1]
```diff
@@ -34,7 +34,7 @@ defmodule ErrorTracker.Web.Router do
       # paths for navigating through the dashboard.
       scoped_path = Phoenix.Router.scoped_path(__MODULE__, path)
       # Generate the session name and session hooks.
-      {session_name, session_opts} = parse_options(opts, scoped_path)
+      {session_name, session_opts} = __parse_options__(opts, scoped_path)
```
Comment (odarriba) [inline lib/error_tracker/web/router.ex:37]: I think it should be like:

```suggestion
      {session_name, session_opts} = ErrorTracker.Web.Router.__parse_options__(opts, scoped_path)
```

**Review by odarriba — CHANGES_REQUESTED** [review]
Added a comment of a required change to be able to call the parse_options function which is no longer imported

**Review by odarriba — APPROVED** [review]
