### PR TITLE
Fix some exceptions reporting

### LINKED ISSUE #35: Handler ErrorTracker.Integrations.Phoenix has failed and has been detached
Trying to test out the project but I can't seem to get any errors logged. The error occurs at this line https://github.com/elixir-error-tracker/error-tracker/blob/12da0c3fedef9ca0b2007183c614ab588ac03eb2/lib/error_tracker.ex#L116

I put a sample erronous code `1 + "a"` into a LiveView and got the following error:

```
[error] Handler ErrorTracker.Integrations.Phoenix has failed and has been detached. Class=:error
Reason={:badmatch,
 {:error,
  #Ecto.Changeset<
    action: :new,
    changes: %{
      lines: [
        #Ecto.Changeset<
          action: :insert,
          changes: %{function: "+", module: "erlang"},
          errors: [arity: {"is invalid", [type: :integer, validation: :cast]}],
          data: #ErrorTracker.Stacktrace.Line<>,
          valid?: false
        >,
        ...
```

I also tried changing a function call to use an invalid name (changing `AshPhoenix.LiveView.page_from_params` to `AshPhoenix.LiveView.page_from_params1`, and got a similar error:

```
[error] Handler ErrorTracker.Integrations.Phoenix has failed and has been detached. Class=:error
Reason={:badmatch,
 {:error,
  #Ecto.Changeset<
    action: :new,
    changes: %{
      lines: [
        #Ecto.Changeset<
          action: :insert,
          changes: %{
            function: "page_from_params1",
            module: "AshPhoenix.LiveView",
            application: "ash_phoenix"
          },
          errors: [arity: {"is invalid", [type: :integer, validation: :cast]}],
          data: #ErrorTracker.Stacktrace.Line<>,
          valid?: false
        >,
        ...
```

Are these not classes of errors that can be tracked at the moment?

### PR DESCRIPTION
**Pull request by odarriba**
This change updates how some Erlang errors are handled and ensure they are stored and shown properly.

The root issue was that some Erlang errors are received as tuples and we need to convert them to Elixir exception the same way as Phoenix does on their Error pages, by calling `Exception.normalize`.

We also fixed storing and showing stractrace information on those cases in which no file is reported.

Closes #35

### CODE REVIEW

File: lib/error_tracker.ex [hunk 1]
```diff
@@ -101,18 +101,9 @@ defmodule ErrorTracker do
...
-        %struct{} = ex when is_exception(ex) ->
-          {to_string(struct), Exception.message(ex)}
-
-        {_kind, %struct{} = ex} when is_exception(ex) ->
-          {to_string(struct), Exception.message(ex)}
-
-        {kind, ex} ->
-          {to_string(kind), to_string(ex)}
-      end
+    IO.inspect(exception)
```
Comment (Zurga) [inline lib/error_tracker.ex]: Lost debug line

File: lib/error_tracker.ex [hunk 2]
```diff
@@ -180,4 +171,18 @@ defmodule ErrorTracker do
   def get_context do
     Process.get(:error_tracker_context, %{})
   end
+
+  defp normalize_exception(%struct{} = ex, _stacktrace) when is_exception(ex) do
+    {to_string(struct), Exception.message(ex)}
+  end
+
+  defp normalize_exception({kind, ex}, stacktrace) do
```
Comment (Zurga) [inline lib/error_tracker.ex:173]: An exception can also be an atom, such as an `ArithmeticError`. This happened to me just now. 

Exception:

    ** (CaseClauseError) no case clause matching: :badarith
        (error_tracker 0.1.2) lib/error_tracker.ex:105: ErrorTracker.report/3
        (error_tracker 0.1.2) lib/error_tracker/integrations/plug.ex:102: ErrorTracker.Integrations.Plug.report_error/3
        (stocker 0.1.0) lib/stocker_web/router.ex:1: StockerWeb.Router.call/2
        (stocker 0.1.0) lib/stocker_web/endpoint.ex:1: StockerWeb.Endpoint.plug_builder_call/2
        (stocker 0.1.0) deps/plug/lib/plug/debugger.ex:136: StockerWeb.Endpoint."call (overridable 3)"/2
        (stocker 0.1.0) lib/stocker_web/endpoint.ex:1: StockerWeb.Endpoint."call (overridable 4)"/2
        (stocker 0.1.0) lib/stocker_web/endpoint.ex:1: StockerWeb.Endpoint.call/2
        (phoenix 1.7.11) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
        (bandit 1.5.5) lib/bandit/pipeline.ex:124: Bandit.Pipeline.call_plug!/2
        (bandit 1.5.5) lib/bandit/pipeline.ex:36: Bandit.Pipeline.run/4
        (bandit 1.5.5) lib/bandit/http1/handler.ex:12: Bandit.HTTP1.Handler.handle_data/3
        (bandit 1.5.5) lib/bandit/delegating_handler.ex:18: Bandit.DelegatingHandler.handle_data/3
        (bandit 1.5.5) /data/home/jim/git/stocker/deps/thousand_island/lib/thousand_island/handler.ex:379: Bandit.DelegatingHandler.handle_info/2
        (stdlib 4.3.1.4) gen_server.erl:1123: :gen_server.try_dispatch/4
        (stdlib 4.3.1.4) gen_server.erl:1200: :gen_server.handle_msg/6
        (stdlib 4.3.1.4) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

**Review by Zurga — CHANGES_REQUESTED** [review]

File: lib/error_tracker.ex (hunk 2 above)
Comment (odarriba) [reply lib/error_tracker.ex:174]: Thanks for the review! I was able to reproduce it and it was a bug introduced during a refactor made when finishing this change.

I can confirm it already works on my side with the latest commit (https://github.com/elixir-error-tracker/error-tracker/pull/36/commits/28c6c2b453ee2325521d68bfa79bd952c538d966). Could you check if your issue is fixed too? 

Thanks

Comment (Zurga) [reply lib/error_tracker.ex:174]: Yes, I will check it now. Thanks for the quick response. Can't wait to use this in production!

Comment (Zurga) [reply lib/error_tracker.ex:174]: Works great!

**Review by crbelaus — APPROVED** [review]

**Comment by crbelaus** [comment]
I've tested this with multiple kind of errors (arithmetic errors, throws, exits, case clause errors, undefined function errors, etc) and it worked perfectly 👍
